### ISSUE TITLE
Can only set cookies to cookies_max_age

### ISSUE THREAD

**Issue by lewilewilewi** [Etenil/assegai#33]
You ought to be able to pass an expiry into setCookie - currently you can only set cookies for $cookies_max_age

**Comment by Etenil** [comment]
I've committed a fix in branch fix-33-cookies-maxage. Please test if satisfactory.

**Comment by Etenil** [comment]
@lewilewilewi is the fix working?

**Comment by lewilewilewi** [comment]
Sorry, I forgot to come back to this!
There's an issue with getAllCookies where there are two return statements, the new code won't run ever.

**Comment by Etenil** [comment]
@lewilewilewi Sorry about that, I've updated the branch to remove the error, added unit tests to cover it and merged into master.

**Comment by lewilewilewi** [comment]
Forgot to let you know that this is looking good.  Thanks!
