### ISSUE TITLE
Default GET/POST parameters are mangled

### ISSUE THREAD

**Issue by jadatkins** [Etenil/assegai#37]
[These two functions](https://github.com/Etenil/assegai/blob/23a2701/src/assegai/Request.php#L176-L196) will, if the GET or POST parameter doesn't exist, pass the `$default` value through `htmlentities()` instead of just returning it, which is counterintuitive and not what the doc-comment says.

```php
    /**
     * Returns an escaped post variable or default.
     * @param string $varname is the variable's name.
     * @param mixed  $default is the default to be returned if the variable
     * doesn't exist.
     */
    function post($varname, $default = false)
    {
        return $this->sec->clean($this->unsafePost($varname, $default));
    }

    /**
     * Returns an escaped get variable or default.
     * @param string $varname is the variable's name.
     * @param mixed  $default is the default to be returned if the variable
     * doesn't exist.
     */
    function get($varname, $default = false)
    {
        return $this->sec->clean($this->unsafeGet($varname, $default));
    }
```

I'm not sure how you want to structure the code to avoid that, otherwise I'd submit a patch.

**Comment by jadatkins** [comment]
This is a problem for us because we've been passing the saved value from the database in as the `$default` value, to display in a form field. The value from the database is already HTML-escaped, so the form field ends up looking like the user typed a HTML entity into it. The user doesn't notice, and saves `No&amp;eacute;mie` as her name.

**Comment by Etenil** [comment]
@jadatkins I've released this change and your previous pull request as v2.2.9. You should see it pop up on packagist soon.

**Comment by jadatkins** [comment]
Thanks. We have a fork of Assegai now, so we're just merging yours into ours.

**Comment by Etenil** [comment]
@jadatkins while you can have your own fork, do you mind sharing some of your changes?

**Comment by jadatkins** [comment]
We have two changes. I think they're both hacks which are specific to our use. Lemme check.

**Comment by jadatkins** [comment]
Surely you can [see our fork](https://github.com/Etenil/assegai/compare/master...Tutorfair:master)?

**Comment by Etenil** [comment]
Ah silly me, I didn't think of checking there.

**Comment by jadatkins** [comment]
There are three changes. I only understand one of them, which is to take a global variable called `releaseSignature` and put it into `$vars->cacheBustingString`. I don't think that would be very useful. I don't understand the other two changes.
